name: dartabase_migration
version: 0.0.5
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: Serverside Database migration for easy database structure manipulation inspired by Ruby on Rails migrations
homepage: https://github.com/HannesRammer/Dartabase/tree/master/dartabase_migration
dependencies:
  postgresql: any
  sqljocky: any

#  unittest: any