name: dartabase_migration
version: 0.6.0
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: Database Migration stands for version controlled database structure manipulation for MySQL and PGSQL without having to write SQL. inspired by Ruby on Rails models
homepage: https://github.com/HannesRammer/Dartabase/tree/master/dartabase_migration
dependencies:
  postgresql: '0.2.12'
  sqljocky: '0.9.0'
  dartabase_core: '0.2.8'
environment: 
  sdk: ">=0.8.10+6 <2.0.0" 
