name: dartabase_migration
version: 1.1.3
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: Database Migration is a version-controlled database structure manipulation for MySQL(sqljocky) and PGSQL(postgresql) without having to write SQL. now supports scaffolding(database2code) ORM CRUD inspired by Ruby on Rails!!
homepage: https://github.com/HannesRammer/Dartabase/tree/master/dartabase_migration
dependencies:
  postgresql: "^0.3.3"
  sqljocky: "^0.14.1"
  sqlite: ^0.3.0
  dartabase_core: "^0.5.2"
    #path: "c:/Projects/Dart/dartabase/dartabase_core"
  #dependencies used for web interface
  params: "^0.0.3"
    #path: "c:/Projects/Dart/Params"
  #routing dependencies
  route: "^0.4.6"
  routes: '^0.1.4'
    #path: "C:/Projects/Dart/routes"
  #visuals
  polymer_elements: "^1.0.0-rc.8"
  polymer: "^1.0.0-rc.16"
  web_components: "^0.12.0"
  reflectable: "^0.5.2"
  #observe: "^0.13.4"
  #template_binding: "^0.14.0+4"
  analyzer: ">=0.27.0 <0.27.2"
environment:
  sdk: ">=1.12.0 <2.0.0"
transformers:
- polymer:
    entry_points: web/tool/index.html
  