name: dartabase_core
version: 0.6.0+1
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: Dartabase core lib used by Dartabase tools
homepage: http://dartabase-app.appspot.com/
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  dev_string_converter: '>=0.1.0 <1.0.0'
