name: dartabase_core
version: 0.2.10
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: Dartabase core lib used by Dartabase tools
homepage: https://github.com/HannesRammer/Dartabase/tree/master/dartabase_core
environment:
  sdk: '>=0.8.10+6 <2.0.0'
