name: dartabase_model
version: 1.1.3
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: "Database Model is for simple dot notation data manipulation for MySQL and PGSQL without having to write SQL. Inspired by Ruby on Rails"
homepage: https://github.com/HannesRammer/Dartabase/tree/master/dartabase_model
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  dartabase_core: #"^0.5.2"
    path: "/home/hannes/Projects/Dartabase/dartabase_core"
    #path: "c:/Projects/Dart/dartabase/dartabase_core"
    #path: "/home/hannes/Projects/Dartabase/dartabase_core"
  json_object: '>=1.0.18+2 <1.1.0'
  postgresql: "^0.3.3"
  sqljocky2: "^0.14.4-dev"
  sqlite: "^0.4.0"