name: dartabase_model
version: 0.4.1
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: Serverside Database models for easy database data manipulation inspired by Ruby on Rails models for mysql and postgresql
homepage: https://github.com/HannesRammer/Dartabase/tree/master/dartabase_model
dependencies:
  postgresql: '0.2.12'
  sqljocky: '0.9.0'
  dartabase_core: '0.2.3'
  json_object: '1.0.18+2'
environment: 
  sdk: ">=0.8.10+6 <2.0.0" 