name: dartabase_model
version: 0.7.0
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: "Database Models is for simple data manipulation for MySQL and PGSQL\
  \ without having to write SQL.\r\ninspired by Ruby on Rails models"
homepage: https://github.com/HannesRammer/Dartabase/tree/master/dartabase_model
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  dartabase_core: '>=0.3.0 <0.4.0'
  json_object: '>=1.0.18+2 <1.1.0'
  postgresql: '>=0.2.14 <0.3.0'
  sqljocky: '>=0.11.0 <0.12.0'