name: dartabase_model
version: 0.5.4
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: Serverside Database models for easy database data manipulation inspired by Ruby on Rails models for mysql and postgresql
homepage: https://github.com/HannesRammer/Dartabase/tree/master/dartabase_model
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  dartabase_core: 0.2.3
  json_object: 1.0.18+2
  postgresql: 0.2.12
  sqljocky: 0.9.0
