name: dartabase_model
version: 1.0.0
author: Hannes Rammer <Hannes.Rammer@gmail.com>
description: "Database Model is for simple dot notation data manipulation for MySQL and PGSQL without having to write SQL. Inspired by Ruby on Rails"
homepage: https://github.com/HannesRammer/Dartabase/tree/master/dartabase_model
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  dartabase_core: "^0.4.0"
    #path: "c:/Projects/Dart/dartabase/dartabase_core"
  json_object: '>=1.0.18+2 <1.1.0'
  postgresql: "^0.3.3"
  sqljocky: "^0.14.1"