name: PostTutorialMixApp
description: A sample command-line application
dev_dependencies:
  dartabase_model: '0.5.6'
  json_object: ">=1.0.18+2 <2.0.0"
  browser: any
  polymer: any
transformers:
- polymer:
    entry_points: web/index.html
  